### ISSUE TITLE
Can't build ignition-qt on Linux due to OpenSSL 1.1 incompatibility

### ISSUE THREAD

**Issue by feyrian** [ignitioncoin/ignitioncoin#30]
System: Linux Mint 17.3 Cinnamon 64-bit
Kernel: 3.19.0-42-generic

When trying to build the Ignition-qt  for Linux I got 2 errors.

First, permissions errors, easy to fix, just give execute perm (chmod +x) for:
- src/leveldb/build_detect_platform
- src/secp256k1/autogen.sh
_-> maybe add this chmod instruction on doc/readme-qt.rst_

Second, tests errors, don't know how to fix this, I'm stuck here:

```gcc -I. -g -O2 -Wall -Wextra -Wno-unused-function -c src/gen_context.c -o gen_context.o
gcc gen_context.o -o gen_context
./gen_context
  CC       src/libsecp256k1_la-secp256k1.lo
  CCLD     libsecp256k1.la
  CC       src/tests-tests.o
src/tests.c: In function ‘test_ecdsa_der_parse’:
src/tests.c:3561:52: error: dereferencing pointer to incomplete type
         valid_openssl = !BN_is_negative(sig_openssl->r) && !BN_is_negative(sig_openssl->s) && BN_num_bits(sig_openssl->r) > 0 && BN_num_bits(sig_openssl->r) <= 256 && BN_num_bits(sig_openssl->s) > 0 && BN_num_bits(sig_openssl->s) <= 256;
                                                    ^
src/tests.c:3561:87: error: dereferencing pointer to incomplete type
         valid_openssl = !BN_is_negative(sig_openssl->r) && !BN_is_negative(sig_openssl->s) && BN_num_bits(sig_openssl->r) > 0 && BN_num_bits(sig_openssl->r) <= 256 && BN_num_bits(sig_openssl->s) > 0 && BN_num_bits(sig_openssl->s) <= 256;
                                                                                       ^
src/tests.c:3561:118: error: dereferencing pointer to incomplete type
         valid_openssl = !BN_is_negative(sig_openssl->r) && !BN_is_negative(sig_openssl->s) && BN_num_bits(sig_openssl->r) > 0 && BN_num_bits(sig_openssl->r) <= 256 && BN_num_bits(sig_openssl->s) > 0 && BN_num_bits(sig_openssl->s) <= 256;
                                                                                                                      ^
src/tests.c:3561:153: error: dereferencing pointer to incomplete type
         valid_openssl = !BN_is_negative(sig_openssl->r) && !BN_is_negative(sig_openssl->s) && BN_num_bits(sig_openssl->r) > 0 && BN_num_bits(sig_openssl->r) <= 256 && BN_num_bits(sig_openssl->s) > 0 && BN_num_bits(sig_openssl->s) <= 256;
                                                                                                                                                         ^
src/tests.c:3561:191: error: dereferencing pointer to incomplete type
         valid_openssl = !BN_is_negative(sig_openssl->r) && !BN_is_negative(sig_openssl->s) && BN_num_bits(sig_openssl->r) > 0 && BN_num_bits(sig_openssl->r) <= 256 && BN_num_bits(sig_openssl->s) > 0 && BN_num_bits(sig_openssl->s) <= 256;
                                                                                                                                                                                               ^
src/tests.c:3561:226: error: dereferencing pointer to incomplete type
         valid_openssl = !BN_is_negative(sig_openssl->r) && !BN_is_negative(sig_openssl->s) && BN_num_bits(sig_openssl->r) > 0 && BN_num_bits(sig_openssl->r) <= 256 && BN_num_bits(sig_openssl->s) > 0 && BN_num_bits(sig_openssl->s) <= 256;
                                                                                                                                                                                                                                  ^
src/tests.c:3564:34: error: dereferencing pointer to incomplete type
             BN_bn2bin(sig_openssl->r, tmp + 32 - BN_num_bytes(sig_openssl->r));
                                  ^
In file included from src/tests.c:21:0:
src/tests.c:3564:74: error: dereferencing pointer to incomplete type
             BN_bn2bin(sig_openssl->r, tmp + 32 - BN_num_bytes(sig_openssl->r));
                                                                          ^
src/tests.c:3569:34: error: dereferencing pointer to incomplete type
             BN_bn2bin(sig_openssl->s, tmp + 32 - BN_num_bytes(sig_openssl->s));
                                  ^
In file included from src/tests.c:21:0:
src/tests.c:3569:74: error: dereferencing pointer to incomplete type
             BN_bn2bin(sig_openssl->s, tmp + 32 - BN_num_bytes(sig_openssl->s));
                                                                          ^
make[1]: *** [src/tests-tests.o] Erreur 1
```

**Comment by fopat** [comment]
Which version of OpenSSL are you using?
IC does not compile with OpenSSL 1.1 due to changes to the BigNum type (BN).
I had to uninstall OpenSSL 1.1 includes and libs and install OpenSSL 1.0.2 (package libssl1.0-dev on Debian).

**Comment by AmirWaleed** [comment]
You can give the files permission with `chmod +x 'filename.x'`

**Comment by feyrian** [comment]
My version of OpenSSL is effectively 1.1.0g
Is it doable to make IC compatible with this version as it is the last one and the one available with new systems ?
I don't want to mess my system removing it.
If I do a apt-get remove openssl it tells me that many packages will be removed too, like google-chrome-stable, hplip, ruby, ruby-json, ruby1.9.1, ruby2.0, smartgit, ssl-cert...

**Comment by TechniumUnlimited** [comment]
@feyrian Just use chmod +x on the questionable files for now

**Comment by feyrian** [comment]
@TechniumUnlimited The execute perm is not the issue here, as I wrote I gave execute perm for the two files. It was just to point steps not working while trying to compile. I've edited my first post to clarify.

But after that, there is errors with the tests, as @fopat said it is related to the OpenSSL version.
IC is not compatible with the last version -> OpenSSL v1.1
A solution would be to remove this version and install the previous one (v1.0.2) but I don't want to mess with my system.
So I asked if this is doable to make IC compatible with OpenSSL v1.1 or not ? I really don't have a clue to the workload it represents.

**Comment by fopat** [comment]
Fix merged on openssl-compat.
Needs a beta testing to make sure everything is working as intended.

**Comment by TechniumUnlimited** [comment]
@feyrian would you mind trying it out :]

**Comment by TechniumUnlimited** [comment]
@fopat This was merged correct?

**Comment by fopat** [comment]
@TechniumUnlimited Yes, but on the openssl-compat branch, not on the dev branch.

**Comment by TechniumUnlimited** [comment]
eek :D https://github.com/ignitioncoin/ignitioncoin/pull/33
